parameters:
- name: repo
  type: string
  default:
- name: project
  type: string
  default:

variables:
  releaseExists: false
  version:

jobs:
- job:
  pool:
    vmImage: 'ubuntu-latest'

  steps:

    - task: PowerShell@2
      displayName: Set version
      inputs:
        targetType: 'inline'
        script: |
          $csprojVersion = ([xml](Get-Content '${{ parameters.project }}/${{ parameters.project }}.csproj')).Project.PropertyGroup.Version
          Write-Host "##vso[task.setvariable variable=version;]$csprojVersion"


    - task: DotNetCoreCLI@2
      displayName: Restore
      inputs:
        command: restore
        projects: '$(Parameters.RestoreBuildProjects)'


    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        projects: '$(Parameters.RestoreBuildProjects)'
        arguments: '--configuration $(BuildConfiguration)'

    - task: NuGetCommand@2
      displayName: 'NuGet pack'
      inputs:
        command: pack

    - task: NuGetCommand@2
      displayName: 'NuGet push'
      inputs:
        command: push
        nuGetFeedType: external
        publishFeedCredentials: NuGet

    - task: PowerShell@2
      displayName: Check GitHub release
      inputs:
        targetType: 'inline'
        script: |
          $releaseExists = (Invoke-RestMethod -SkipHttpErrorCheck -Uri 'https://api.github.com/repos/johnwatson484/${{ parameters.repo }}/releases/tags/$(version)').tag_name -eq '$(version)'
          Write-Host "##vso[task.setvariable variable=releaseExists;]$releaseExists"

    - task: GitHubRelease@1
      displayName: GitHub release
      inputs:
        gitHubConnection: 'John D Watson PAT'
        repositoryName: '$(Build.Repository.Name)'
        action: 'create'
        target: '$(Build.SourceVersion)'
        tagSource: 'userSpecifiedTag'
        tag: '$(version)'
        title: '$(version)'
        releaseNotesSource: 'inline'
        changeLogCompareToRelease: 'lastFullRelease'
        changeLogType: 'commitBased'
      continueOnError: true
      condition: and(succeeded(), eq(variables.releaseExists, false))
